# Generated by Django 4.2.20 on 2025-05-24 16:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="topic",
            name="deleted",
            field=models.BooleanField(default=False),
        ),
    ]
