# Generated by Django 4.2.20 on 2025-05-25 04:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notes", "0002_topic_deleted"),
    ]

    operations = [
        migrations.AddField(
            model_name="topic",
            name="category",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="topic",
            name="content",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="topic",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
