# Generated by Django 4.2.20 on 2025-06-01 13:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notes", "0005_noteitem_deleted_noteitem_deleted_at_noteitem_order_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="noteitem",
            name="title",
            field=models.TextField(blank=True),
        ),
    ]
