# Generated by Django 4.2.20 on 2025-06-02 06:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("notes", "0006_noteitem_title"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="noteitem",
            name="deleted_at",
        ),
        migrations.RemoveField(
            model_name="noteitem",
            name="order",
        ),
        migrations.RemoveField(
            model_name="noteitem",
            name="updated_at",
        ),
    ]
