# Generated by Django 4.2.20 on 2025-06-02 15:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notes", "0007_remove_noteitem_deleted_at_remove_noteitem_order_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="noteitem",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="note_photos/"),
        ),
    ]
