# Generated by Django 4.2.20 on 2025-06-03 17:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("notes", "0008_noteitem_photo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="noteitem",
            name="photo",
        ),
        migrations.AddField(
            model_name="noteitem",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="topic",
            name="shared_with",
            field=models.ManyToManyField(
                blank=True, related_name="shared_topics", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="noteitem",
            name="title",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
