# Generated by Django 4.2.20 on 2025-06-04 13:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("notes", "0009_remove_noteitem_photo_noteitem_updated_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="noteitem",
            name="last_edited_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="edited_notes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
